
--DROP TABLE USUARIO;
CREATE TABLE USUARIO(   --CREANSDO TABLA USUARIO
    RUNUSUARIO NUMBER(9) CONSTRAINT USUARIO_PK PRIMARY KEY, 
	USNOMBRE VARCHAR2(30) CONSTRAINT USUARIO_nn1 NOT NULL, 
	USAPELLIDO VARCHAR2(50) CONSTRAINT USUARIO_nn2 NOT NULL, 
	USNACIMIENTO VARCHAR2(10)
);

--DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(   --CREANDO TABLA CLIENTE  perfil 1
    RUTCLIENTE NUMBER(9) CONSTRAINT CLIENTE_PK PRIMARY KEY, 
	CLITELEFONO VARCHAR2(20) CONSTRAINT CLIENTE_nn1 NOT NULL , 
	CLIAFP VARCHAR2(30), 
	CLISISTEMASALUD NUMBER(2), 
	CLIDIRECCION VARCHAR2(100)CONSTRAINT CLIENTE_nn2 NOT NULL, 
	CLICOMUNA VARCHAR2(50)CONSTRAINT CLIENTE_nn3 NOT NULL, 
	CLIEDAD NUMBER(3) CONSTRAINT CLIENTE_nn4 NOT NULL,
    USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT CLIENTE_nn5 NOT NULL
);

--DROP TABLE ADMINISTRATIVO;
CREATE TABLE ADMINISTRATIVO (   --CREANDO TABLA ADMINISTRATIVO PERFIL 2
    USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT ADMINISTRATIVO_PK PRIMARY KEY,
    ADCORREO VARCHAR2(70),
    ADAREA VARCHAR2(20) CONSTRAINT ADMINISTRATIVO_NN1 NOT NULL
);

--DROP TABLE PROFESIONAL;
CREATE TABLE PROFESIONAL(   --Creando Tabla PROFESIONAL perfil 3
    USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT PROFESIONAL_PK PRIMARY KEY,
    PROTELEFONO VARCHAR(12),
    PROTITULO VARCHAR(50)CONSTRAINT PROFESIONAL_nn1 NOT NULL,
    PROPROYECTO VARCHAR(50)
);

--DROP TABLE CAPACITACION;
CREATE TABLE CAPACITACION(   --CREANDO TABLA CAPACITACION
    IDCAPACITACION NUMBER(9) CONSTRAINT CAPACITACION_PK PRIMARY KEY,
    CAPFECHA VARCHAR2(10) CONSTRAINT CAPACITACION_nn1 NOT NULL ,
    CAPHORA VARCHAR2(5),
    CAPLUGAR VARCHAR2(100) CONSTRAINT CAPACITACION_nn2 NOT NULL,
    CAPDURACION NUMBER(4),
    CLIENTE_RUTCLIENTE NUMBER(9) CONSTRAINT CAPACITACION_nn3 NOT NULL
);

-- CREANDO FOREIGN KEY
ALTER TABLE CLIENTE   --LLAVE FORANEA  CLIENTE
ADD CONSTRAINT CLIENTE_USUARIO_FK
FOREIGN KEY(USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO); 

ALTER TABLE ADMINISTRATIVO   --LLAVE FORANEA  ADMINISTRATIVO
ADD CONSTRAINT ADMINISTRATIVO_USUARIO_FK
FOREIGN KEY (USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO);

ALTER TABLE PROFESIONAL   --LLAVE FORANEA  PROFESIONAL 
ADD CONSTRAINT PROFESIONAL_USUARIO_FK
FOREIGN KEY(USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO);

ALTER TABLE CAPACITACION   --LLAVE FORANEA  CAPACITACION
ADD CONSTRAINT CAPACITACION_CLIENTE_FK
FOREIGN KEY(CLIENTE_RUTCLIENTE)
REFERENCES CLIENTE(RUTCLIENTE);

--IDENTIFICADOR CORRELATIVO AUINCREMENTAL - TABLA CAPACITACION
CREATE SEQUENCE IDCAPACITACION_SEQ   --SECUENCIA 
MINVALUE 7
INCREMENT BY 1 ;

CREATE OR REPLACE TRIGGER IDCAPACITACION_TRIGGER --DISPARADOR 
BEFORE INSERT ON CAPACITACION 
FOR EACH ROW
WHEN(NEW.IDCAPACITACION IS NULL)
BEGIN
SELECT IDCAPACITACION_SEQ.NEXTVAL
INTO:NEW.IDCAPACITACION
FROM dual;
END;
/

